version: '3'

services:
  jira-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    networks:
        - my-network
    depends_on:
      - my-redis

  my-redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - my-network

networks:
    my-network:
        driver: bridge
